# Generated by Django 4.1.5 on 2023-01-22 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='img_2',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='img_3',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='img_4',
        ),
    ]
